# Generated by Django 4.2.5 on 2023-09-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_rename_customer_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='name',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='details',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='details',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
