# Generated by Django 4.2.5 on 2023-09-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='verify',
            field=models.CharField(default='Unverified', max_length=200),
        ),
    ]
