# Generated by Django 4.2.5 on 2023-09-11 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broker', '0008_deposit_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('account_number', models.CharField(default='0.00', max_length=200, null=True)),
                ('account_name', models.CharField(default='0.00', max_length=200)),
                ('bank_name', models.CharField(default='0.00', max_length=200)),
                ('swift_code', models.CharField(default='0.00', max_length=200)),
                ('bitcoin_address', models.CharField(default='0.00', max_length=200, null=True)),
                ('ethereum_address', models.CharField(default='0.00', max_length=200)),
                ('cashapp_tag', models.CharField(default='0.00', max_length=200)),
                ('paypal_email', models.CharField(default='0.00', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
