# Generated by Django 4.2.5 on 2023-09-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0010_rename_details_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='name',
        ),
    ]
