# Generated by Django 4.2.5 on 2023-09-11 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broker', '0011_rename_full_name_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactiontwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(default='-', max_length=200)),
                ('tf_type', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(default='-', max_length=200)),
                ('tf_type', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactionone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(default='-', max_length=200)),
                ('tf_type', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(default='-', max_length=200)),
                ('tf_type', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
