# Generated by Django 4.2.5 on 2023-09-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0012_transactiontwo_transactionthree_transactionone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='number',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionone',
            name='number',
            field=models.CharField(default='2', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionthree',
            name='number',
            field=models.CharField(default='4', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactiontwo',
            name='number',
            field=models.CharField(default='3', max_length=200),
        ),
    ]
