# Generated by Django 5.0.3 on 2024-03-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0015_remove_deposit_gift_cards_remove_deposit_profit_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='capital_balance',
            field=models.CharField(default='0.00', max_length=200),
        ),
    ]
