# Generated by Django 5.0.6 on 2024-06-10 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0019_remove_transactionone_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoin',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='bitcoin',
            name='number',
        ),
        migrations.RemoveField(
            model_name='bitcoin',
            name='tf_type',
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='amount',
            field=models.CharField(blank=True, default='$10', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bitcoin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
