# Generated by Django 5.0.6 on 2024-06-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0024_rename_last_name_kyc_ccode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='fname',
            new_name='name',
        ),
    ]
