# Generated by Django 5.0.6 on 2024-06-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0025_rename_fname_kyc_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kyc',
        ),
    ]
