# Generated by Django 5.0.6 on 2024-06-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0029_kyc_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='ccode',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='pnumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='idback',
            new_name='valid_id_back',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='idfront',
            new_name='valid_id_front',
        ),
    ]
