# Generated by Django 5.1.4 on 2025-01-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0031_remove_deposit_btc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='bonus_usd',
            new_name='bonus',
        ),
    ]
