# Generated by Django 5.1.4 on 2025-01-02 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0033_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin',
            field=models.CharField(default='1991', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Alert1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('alert', models.CharField(choices=[('sweetAlert', 'click on to show'), ('paid', 'mark as paid')], default='sweetAlert', max_length=24)),
                ('status', models.CharField(choices=[('Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info', 'Please upgrade your account, your current investment plan does not support this action, the company will email you shortly or contact customer care for more info')], default='Please upgrade your account, your current investment plan does not support this transfer, the company will email you shortly or contact customer care for more info.', max_length=200, null=True)),
                ('kyc', models.CharField(choices=[('swal-2', 'swal-2'), ('swal-4', 'swal-4')], default='#swal-4', max_length=24)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('alert', models.CharField(choices=[('sweetAlert', 'click on to show'), ('paid', 'mark as paid')], default='sweetAlert', max_length=24)),
                ('status', models.CharField(choices=[('KYC has not been uploaded kindly fill in your details on your kyc data table and contact customer care', 'KYC has not been uploaded kindly fill in your details on your kyc data table and contact customer care')], default='KYC has not been uploaded kindly fill in your details on your kyc data table.', max_length=200, null=True)),
                ('kyc', models.CharField(choices=[('swal-2', 'swal-2'), ('swal-4', 'swal-4')], default='#swal-4', max_length=24)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
