# Generated by Django 5.1.4 on 2025-01-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0034_alter_pin_pin_alert1_alert2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert1',
            name='alert',
            field=models.CharField(choices=[('sweetAlert', 'click on to show'), ('paid', 'mark as paid')], default='paid', max_length=24),
        ),
    ]
