# Generated by Django 5.2.6 on 2025-09-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0035_alter_alert1_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='usd',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='verify',
        ),
    ]
